spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    hikari:
      username: future
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:oracle:thin:@localhost:1521:xe
      password: future
      minimum-idle: '3'
#      username: admin
#      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#      jdbc-url: jdbc:log4jdbc:oracle:thin:@golflearn_medium?TNS_ADMIN=wallet/Wallet_golflearn
#      password: Dalmo08230823
#      minimum-idle: '3'
  jpa:
    generate-ddl: 'true'
    database: oracle
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
        format_sql: 'true'
#  servlet:
#    multipart:
#      location: C:\Project\GolfLearn\front\src\main\webapp\
server:
  servlet:
    context-path: /backresale
  port: '1126'