spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 'true'
    database-platform: org.hibernate.dialect.Oracle10gDialect
    database: oracle
    show-sql: 'true'
  thymeleaf:
    cache: 'false'
    prefix: classpath:src/main/resources/templates
    check-template-location: 'true'
    suffix: .html
    order: '0'
    mode: HTML5
  main:
    banner-mode: console
  devtools:
    restart:
      enabled: 'false'
    livereload:
      enabled: 'true'
  datasource:
    hikari:
      username: future
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:oracle:thin:@localhost:1521:xe
      password: future
      minimum-idle: '3'
#      password: Dalmo08230823
#      username: admin
#      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#      jdbc-url: jdbc:log4jdbc:oracle:thin:@golflearn_medium?TNS_ADMIN=wallet/Wallet_golflearn
#      minimum-idle: '3'
  freemarker:
    cache: 'false'
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 15MB
      location: c:\files
  jackson:
    serialization:
      fail-on-empty-beans: 'false'
server:
  port: '1129'
  servlet:
    context-path: /backmeet