spring:
  datasource:
    hikari:
#      username: admin
#      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#      # jdbc-url: jdbc:log4jdbc:oracle:thin:@golflearn_medium?TNS_ADMIN=C:/Project/wallet/Wallet_golflearn
#      jdbc-url: jdbc:log4jdbc:oracle:thin:@golflearn_medium?TNS_ADMIN=wallet/Wallet_golflearn
#      password: Dalmo08230823
#      minimum-idle: '3'
#      driver-class-name : net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#      jdbc-url : jdbc:log4jdbc:oracle:thin:@localhost:1521:xe
#      username : hr
#      password : hr
#      minimum-idle : 2
      username: future
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:oracle:thin:@localhost:1521:xe
      password: future
      minimum-idle: '3'
  jpa:
    generate-ddl: 'true'
    database: oracle
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
        format_sql: 'true'
  main:
    banner-mode: console
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 15MB
      location: C:\\Project\\GolfLearn\\front\\src\\main\\webapp\\
#logging:
#  charset:
#    console: UTF-8
#  level:
#    org:
#      hibernate: error
#    root: error
server:
  servlet:
    context-path: /backroundreview
  port: '1125'