spring:
  datasource:
    hikari:
      username: future
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:oracle:thin:@localhost:1521:xe
      password: future
      minimum-idle: '3'
      # 테스트용 로컬 DB ▲
      
#      username: admin
#      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#      jdbc-url: jdbc:log4jdbc:oracle:thin:@golflearn_medium?TNS_ADMIN=wallet/Wallet_golflearn
#      password: Dalmo08230823
#      minimum-idle: '3'
  jpa:
    generate-ddl: 'true'
    open-in-view: 'false'
    database: oracle
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
        format_sql: 'true'
  main:
    banner-mode: console
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 150MB
      location: C:\Project\GolfLearn\front\src\main\webapp\notice_image\
      
  output:
    ansi:
      enabled: ALWAYS
logging:
  charset:
    console: UTF-8
  level:
    org:
      hibernate: info
    root: 'info'
server:
  servlet:
    context-path: /noticeboard
  port: '1128'